apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mohz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-mohz@sha256:dfca8b9f7ee4a97388e830f2daae63949495a7ed66ec70bda494ececd0f524c6
        name: my-nodejs
        resources: {}
status: {}
